var skills = {
	languages: [
		{ label: 'Java', level: 10 },
		{ label: 'Scala', level: 10 },
		{ label: 'HTML5', level: 6 },
		{ label: 'CSS3', level: 6 },
		{ label: 'JavaScript', level: 8 },
		{ label: 'Node JS', level: 4 },
		{ label: 'Python', level: 3 },
		{ label: 'SQL', level: 4 },
		{ label: 'C', level: 2 },
		{ label: 'C++', level: 2 },
		{ label: 'C#', level: 6 },
		{ label: 'Apex', level: 5 },
		{ label: 'Aura Components', level: 5 },
		{ label: 'Lightning Web Components', level: 1 },
	],
	apis: [
		{ label: 'Firebase', level: 6 },
		{ label: 'Stripe', level: 8 },
		{ label: 'Plaid', level: 8 },
		{ label: 'Twilio', level: 3 },
		{ label: 'Mailgun', level: 3 },
		{ label: 'Youtube', level: 3 },
		{ label: 'TagMe', level: 5 },
		{ label: 'Google Cloud Platform', level: 7 },
		{ label: 'web3j', level: 3 },
		{ label: 'Loopring', level: 3 },
		{ label: 'Wyre', level: 9 },
	],
	libraries: [
		{ label: 'Play! Framework', level: 6 },
		{ label: 'Akka', level: 4 },
		{ label: 'Socket IO', level: 4 },
		{ label: 'Bootstrap', level: 8 },
		{ label: 'Chrome Extension', level: 7 },
		{ label: 'JQuery', level: 5 },
		{ label: 'Google 2FA', level: 3 },
		{ label: 'Heroku', level: 3 },
		{ label: 'Docker', level: 3 },
		{ label: 'Bukkit', level: 6 },
	],
	tools: [
		{ label: 'Git', level: 8 },
		{ label: 'GitHub', level: 8 },
		{ label: 'IntelliJ', level: 8 },
		{ label: 'Visual Studio Code', level: 5 },
		{ label: 'Postman', level: 5 },
		{ label: 'Unity', level: 3 },
	],
	design: [
		{ label: 'Adobe Illustator', level: 10 },
		{ label: 'Photoshop', level: 5 },
		{ label: 'Blender', level: 3 },
	]
};
